pipeline:
    docker:
      image: plugins/docker:latest
      environment:
        - DOCKER_LAUNCH_DEBUG=true
      repo: santosh.hirekerur/cook-webhook
      tag: santosh.hirekerur/cook-webhook
      file: Dockerfile
      when:
        event: push # only run on merge into master
        branch: [master]
        status: [changed]
