pipeline:
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: http://192.168.99.100:3000/santosh.kumar/cook-webhook
    tags: latest
    dockerfile: Dockerfile
    compose:
      from-file: docker-compose.yml
