pipeline:
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: santosh.kumar/cook-webhook
    tags: latest
    dockerfile: ./cook-webhook/Dockerfile
    compose:
      from-file: docker-compose.yml
