FROM almir/webhook

MAINTAINER Santhosh Hirekerur <santhosh.hirekerur@tayloredtechnology.net>

# 0@Cache -- Perma-Cached
# Applications that don't automatically link to the docker logs standard output go here
#RUN ln -sf /dev/stdout /var/log/nginx/access.log
# Important for all Debian based distributions
ENV DEBIAN_FRONTEND=noninteractive

# Volumes
VOLUME /grid-discovery

# Service Required Ports
EXPOSE 9000

# 1@Cache -- installs / binaries slow changing items
ENV REFRESHED_AT 2016-10-05

# In Alpine continers don't need to manually delete things --no-cache will clean up after itself
RUN apk --no-cache add jq


RUN mkdir -p /etc/webhook/scripts && mkdir -p /etc/webhook/data
ADD hooks.json /etc/webhook/hooks.json

# 2@Cache -- always Bust Cache to ensure pulling latest committed version
# Cook Medical will need to take out their own subscription to this service
#ADD https://www.amdoren.com/api/timezone.php?api_key=((insert key))&loc=Brisbane /tmp/bustcache
ADD /scripts /etc/webhook/scripts/
ADD /data /etc/webhook/data/
RUN chmod a+x /etc/webhook/scripts/*.sh

CMD ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload"]
#RUN chmod a+x /etc/webhook/data/*.json

#TODO upgrade to alpine S6 base container then add webhook library to prevent zombie processes (as is currently happening)
