FROM almir/webhook
COPY hooks.json /etc/webhook/hooks.json
#COPY test.sh /etc/webhook/test.sh
#RUN chmod 755 /etc/webhook/test.sh

#####new


#creating scripts folder and copy scripts files
RUN mkdir -p /etc/webhook/scripts
COPY scripts /etc/webhook/scripts/
RUN chmod a+x /etc/webhook/scripts/*.sh

#creating data folder and copy json

RUN mkdir -p /etc/webhook/data
COPY data /etc/webhook/data/
RUN chmod a+x /etc/webhook/data/*.json


# adding jq
RUN apk update \
 && apk add jq \
&& rm -rf /var/cache/apk/*

CMD ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload"]
